MultiGraphClass Rnw conversion to Rmd
Bioconductor/graph pull request #11
Opened 2022-10-25 08:43 UTC by Chisomgold

Hi @jwokaty  

Here's the new branch with changes specific to MultiGraphClass file conversion.

[PDF format](https://bioconductor.org/packages/devel/bioc/vignettes/graph/inst/doc/MultiGraphClass.pdf)
[HTML file](https://github.com/Bioconductor/graph/files/9838551/MultiGraphClass.zip)

2022-10-31 01:58 UTC, villafup commented on vignettes/MultiGraphClass.Rmd
> +We shall load the `r Biocpkg("graph")` and `r Biocpkg("RBGL")` packages that we will be using. We will then create a *MultiGraph* object and then spend some time examining some of the different funct
I see that the external references weren't in the pdf but were in the Rmd.  I think this is ok, but just wanted to point out

2022-10-31 02:01 UTC, villafup commented on vignettes/MultiGraphClass.Rmd
> +We are interested in the gene "10024416717" and the sum of the weights along the path that connects this genes to the other genes for the brain tissue. Since the algorithms in the `r Biocpkg("RBGL")`
See comment line #137

2022-10-31 02:03 UTC, villafup reviewed
Please review 2 comments below.  I don't think that anything needs to be changed.

2022-10-31 05:42 UTC, Chisomgold commented on vignettes/MultiGraphClass.Rmd
> +We shall load the `r Biocpkg("graph")` and `r Biocpkg("RBGL")` packages that we will be using. We will then create a *MultiGraph* object and then spend some time examining some of the different funct
HI @villafup 
Yeah, @jwokaty advised adding the external references while reviewing my conversion of the graphclass sweave file.

2022-11-01 23:02 UTC, jwokaty requested changes
@Chisomgold Thanks for this pull request. Just a few formatting issues to address. I want to also update the DESCRIPTION file so that it states that you also did this vignette. Do you know how to add an "upstream" remote, pull the changes, and rebase? This is so that you'll get the updated code in the Bioconductor/graph repository to your local machine and then you rebase your master on the Bioconductor/graph then rebase your MultiClassGraph-Rmd branch on your updated master branch. We'll have a clean commit history and avoid merge conflicts.

From your repository

```
# Add the original repo by the name "upstream"
# Upstream is just a naming convention
git remote add upstream git@github.com:Bioconductor/graph.git
# Fetch the remote
git fetch upstream
git switch master
# Play the history of upstream master branch on to your master branch
git rebase upstream/master
git switch MultiClassGraph-Rmd
# Play the history of your local master onto your MultiClassGraph-Rmd branch
git rebase master
```

Then make the changes to the DESCRIPTION file. If you run into issues, you can reach out to me on slack.

2022-11-01 23:03 UTC, jwokaty commented
@villafup Thanks for reviewing!

2022-11-03 15:15 UTC, Chisomgold commented on vignettes/MultiGraphClass.Rmd
> +            stringsAsFactors = TRUE)
Hi @jwokaty 

I think I've done that. Please take a look

2022-12-03 21:57 UTC, jwokaty requested changes
Hi @Chisomgold, this looks good. Good job also resolving the conflict with rebasing. Just one change then it's good to merge: let's combine the content from lines 9-14 in the DESCRIPTION so there's one entry for you. The comment could read `"Converted 'MultiGraphClass' and 'GraphClass' vignettes from Sweave to RMarkdown / HTML."`

2022-12-04 05:57 UTC, Chisomgold commented
Hi @jwokaty 

Thanks for the review and the help with rebasing. I've made the requested changes. Please take a look.

2022-12-07 01:29 UTC, merged