Graphattributes rnw
Bioconductor/graph pull request #14
Opened 2023-02-27 22:34 UTC by villafup

@jwokaty for review.  

It was a little tricky resizing graph.  If it's too big I can try making it smaller.

[graphAttributes.pdf](https://github.com/Bioconductor/graph/files/10844864/graphAttributes.pdf)

2023-06-06 08:57 UTC, sonali8434 requested changes
I am doing my first review @villafup I have left 4 reviews I don't think any more changes are required please do the requested modifications.

2023-06-06 08:57 UTC, sonali8434 commented on DESCRIPTION
> +        comment = "Converted 'clusterGraph' and graphAttributes' vignettes from Sweave to RMarkdown / HTML."
We can write here `comment = "Converted vignettes from Sweave to RMarkdown / HTML."` to keep it short if we convert more than one vignette in a package.

2023-06-06 08:57 UTC, sonali8434 commented on DESCRIPTION
>          role = "cre",
I think we need to fix the formatting little bit here you may write:

```
person("Paul", "Villafuerte", role = "ctb",
                comment = "Converted vignettes from Sweave to RMarkdown / HTML."
        ),
person("Bioconductor Package Maintainer", role = "cre",
                email = "maintainer@bioconductor.org"
        ))

2023-06-06 08:57 UTC, sonali8434 commented on vignettes/graphAttributes.Rmd
> +```
I think this code blocked can be modified to get a few correction as we see there is no loading messages are there in original pdf also we see that this code block is hidden in original pdf so we use `echo=Flase` for this purpose alse the height and width parameters are given in .Rnw file so I think we should include that too. 

the modified code chunk should look like 
```
```{r foo, fig.cap="The graph `g1`.", fig.height=6, fig.small=TRUE, fig.width=6, echo=FALSE, message=FALSE, out.extra='id="foo"'}
if (require("Rgraphviz")) {
   gn = as(g1, "graphNEL")
   plot(gn, nodeAttrs=makeNodeAttrs(gn, shape="circle", fillcolor="orange"))
} else {
 plot(1, 1, main="Rgraphviz required for this plot")
}
```
```

2023-06-06 08:57 UTC, sonali8434 commented on vignettes/graphAttributes.Rmd
> +```
I think we also need some help here @jwokaty the original pdf have these lines
```
A graphAM graph with undirected edges
Number of Nodes = 4
Number of Edges = 5
```
but it is not present in the new .html document how to solve this issue?

2023-06-06 08:59 UTC, sonali8434 commented
We will this checklist to review your PR
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- In the `DESCRIPTION` file
  - [ ] `BiocStyle` and `knitr` are listed in `Suggests`
  - [ ] the line `VignetteBuilder: knitr` exists
  - [ ] any added lines use the same spacing and indents as the existing document
- If agreed with the Maintainer
  - [ ] the contributor is in the author list in the `DESCRIPTION` file*.
  - [ ] the contributor is in the author list in the vignette's YAML*.
- If this pull request involves converting from separate `Author` and  `Maintainer`
  lines to the `Authors@R` vector, please ensure that
  - [ ] the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
  - [ ] the `Maintainer` line is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`
- [ ] Only files necessary for the conversion are included in the pull request.
- [ ] Long lines have been broken up and reformatted, you can achieve this by
  selecting the text in your script and then clicking on `Code > Reflow Comment`
  in R Studio.
- [ ] Code blocks are surrounded by a blank line, and there are no blank lines
  before the start or after the end of the code within the code block. 

* Refer to the contribution guide for acceptable formats

2023-06-22 11:54 UTC, villafup commented on DESCRIPTION
> +        comment = "Converted 'clusterGraph' and graphAttributes' vignettes from Sweave to RMarkdown / HTML."
Done.  Also saw that the entry on line 10 also has 2 specific vignettes mentioned as well.

2023-06-22 11:56 UTC, villafup commented on DESCRIPTION
>          role = "cre",
Done.  is this this (and the one before) going to be the standard?  I think we'll have to go through all those we converted to make sure they follow the format.

2023-08-03 15:11 UTC, sonali8434 approved these changes

2023-08-03 15:13 UTC, sonali8434 commented
@jwokaty Please review Thanks @villafup for the changes.

2023-08-08 18:19 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +```
I am asking on another channel if there is a chunk option to do this automatically, but if there isn't, I would suggest just putting `g1` at the end of the code chunk to produce this output.

2023-08-08 18:20 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +```{r exampleGraph2, print=TRUE}
I don't think `print=TRUE` is a valid chunk option in R Markdown. Please remove it.

2023-08-08 18:22 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +```{r other, hide=TRUE, echo=FALSE}
`hide=TRUE` isn't a valid chunk option. Let's remove `hide=TRUE, `.

2023-08-08 18:33 UTC, jwokaty requested changes
Very small changes just to remove chunk options that aren't valid in R Markdown then I think this will be ready to merge. Thanks for this PR.

2023-09-28 13:55 UTC, jwokaty approved these changes

2023-09-28 13:56 UTC, merged