Conversion of graph vignette to RMarkdown file
Bioconductor/graph pull request #19
Opened 2023-03-14 12:35 UTC by sirjoka

@Bioconductor/sweave2rmd please review my work. I created the RMarkdown file for the graph vignette.
Attached are the HTML [graph.zip](https://github.com/Bioconductor/graph/files/10968584/graph.zip) and the original PDF [graph.pdf](https://github.com/Bioconductor/graph/files/10943538/graph.pdf) files for comparison.
Thank you.

2023-03-14 16:21 UTC, jwokaty commented
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- [ ] in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [ ] in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ] any added lines use the same spacing and indents as the existing
  document
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the `DESCRIPTION` file; refer to the contribution guide for acceptable
  formats
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, check that the
  `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line
  is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`

2023-03-14 16:29 UTC, jwokaty commented on vignettes/graph.Rmd
> +[Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) Provides rendering functionality. Different layout algorithms are provided and node plotting, line type, color etc para
Please read https://bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#4_Style_macros to learn how to make canonical links for Bioconductor packages.

2023-03-14 16:30 UTC, jwokaty commented on vignettes/graph.Rmd
> +The reader will benefit greatly from also having the [Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) package available and from using it to
Please use the inline R code to make a link.

2023-03-14 16:30 UTC, jwokaty commented on vignettes/graph.Rmd
> +First we attach the [graph](https://bioconductor.org/packages/release/bioc/html/graph.html) package and create a random graph (this is based on the Erdos-Renyi model for random graphs).
Use inline R code to make the link for this and any other Bioconductor packages in this vignette.

2023-03-14 16:54 UTC, sirjoka commented on vignettes/graph.Rmd
> +[Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) Provides rendering functionality. Different layout algorithms are provided and node plotting, line type, color etc para
Have a look, I think I got it this time.
Thank you

2023-03-14 16:54 UTC, sirjoka commented
I have made the requested corrections needed.
Please review.
Thank you

2023-03-14 16:57 UTC, jwokaty commented on vignettes/graph.Rmd
> +[Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) Provides rendering functionality. Different layout algorithms are provided and node plotting, line type, color etc para
It should be, for example

```
`r Biocpkg("Rgraphviz")`
```

Because I lose the place of the comments when you make a new push, we should coordinate so that I can do a few review items then you can address them. I will stop reviewing for the moment and come back later.

2023-03-14 17:15 UTC, alatiku commented on vignettes/graph.Rmd
> +[Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) Provides rendering functionality. Different layout algorithms are provided and node plotting, line type, color etc para
Ok. There is no need for a link then to the package landing page?

2023-03-14 18:03 UTC, jwokaty commented on vignettes/graph.Rmd
> +[Rgraphviz](https://bioconductor.org/packages/release/bioc/html/Rgraphviz.html) Provides rendering functionality. Different layout algorithms are provided and node plotting, line type, color etc para
The inline code `r Biocpkg("graphviz")` will generate the link to the package landing page.

2023-03-14 18:05 UTC, jwokaty commented on vignettes/graph.Rmd
> +The [` r Biocpkg("graph")`](https://bioconductor.org/packages/release/bioc/html/graph.html) package provides an implementation of graphs (the kind with nodes and edges) in R. Software infrastructure
I want to make sure what I am asking is clear so I am providing the following example. This line should be 

    The `r Biocpkg("graph")` package provides an implementation of graphs (the kind with nodes and edges)

2023-03-15 19:10 UTC, sirjoka commented
Hi @jwokaty good afternoon.
Please take a review of the updated file and advice on next line of action.
Thank you

2023-03-17 15:17 UTC, sirjoka commented
Hi, @jwokaty Please review when free. Thank you

2023-03-17 21:05 UTC, jwokaty commented on vignettes/graph.Rmd
> +```{r message=FALSE, warning=FALSE}
Please add the names of the code blocks. You can see the name of this code block in the .Rnw at https://github.com/Bioconductor/graph/pull/19/files#diff-16c57b04961ffb24e0c39cb848d65d563739c74775c49a141e2e98c1b2916a86L72.

2023-03-17 21:09 UTC, jwokaty commented on vignettes/graph.Rmd
> +The `r Biocpkg("graph")` package provides an implementation of graphs (the kind with nodes and edges) in R. Software infrastructure is provided by three different, but related packages,
Please wrap long lines, such as these. If you recall, this is a question we asked in the knowledge quiz.

2023-03-17 21:11 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate lines 47-62 into a single code block as in the .Rnw.

2023-03-17 21:13 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate lines 68-79 into a single code block as in the .Rnw

2023-03-17 21:14 UTC, jwokaty commented on vignettes/graph.Rmd
> +New graphs can be constructed from these graphs in many different ways but in all cases the existing graph itself is not altered, but rather a copy is made and the changes are carried out on that cop
For functions, please use backticks to indicate that they are functions rather than `**`. Please do this for other functions in this vignette.

2023-03-17 21:14 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate into a single code block as in .Rnw

2023-03-17 21:15 UTC, jwokaty commented on vignettes/graph.Rmd
> +**complement** to be the graph with the same set of nodes as its input and edges in the complement if there were none in the original graph.
Again, use backticks for function names.

2023-03-17 21:15 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate into a single code block.

2023-03-17 21:15 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate into a single code block

2023-03-17 21:16 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate into a single code block

2023-03-17 21:16 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Consolidate into a single code block

2023-03-17 21:20 UTC, jwokaty requested changes
Hi @sirjoka , Please make the following changes to consolidate code blocks, add their names from the .Rnw, wrap long lines, and use backticks for functions. After you make these changes, please notify me so that I can continue the review.

2023-03-17 21:43 UTC, sirjoka commented on vignettes/graph.Rmd
> +```
Ok I thought about that, but isn't that going to alter the flow of the HTML against what the PDF looks like.
Code
Result
Code 
Result
...

Now it will be
Code
Result
Result
.......

Should I still go ahead?

2023-03-17 22:36 UTC, sirjoka commented on vignettes/graph.Rmd
> +**complement** to be the graph with the same set of nodes as its input and edges in the complement if there were none in the original graph.
These are actually operations and are BOLD in the PDF. Should I still replace with backticks?

2023-03-17 23:22 UTC, jwokaty commented on vignettes/graph.Rmd
> +```
Please try  consolidating this into a single code block and knitting to see what actually happens. Compare with the PDF.

2023-03-17 23:24 UTC, jwokaty commented
Maybe you answered your own question about the code blocks? I tried commenting and then I saw your comment disappear. If you are still thinking about it, I suggest you try consolidating one and inspecting both the PDF and HTML to understand how the code blocks are working.

2023-03-17 23:31 UTC, jwokaty commented on vignettes/graph.Rmd
> +**complement** to be the graph with the same set of nodes as its input and edges in the complement if there were none in the original graph.
I know these bold, so you weren't incorrect in choosing to make them bold; however, graph is a really old but important Bioconductor package, so I think this was done before we had some standards/formatting specific to functions. I want them to look similar to other functions in our documention, so I have asked you to use backticks. I'm sorry that I didn't think to explain this, but I am glad you brought up so that I can clarify that this is not an error on your part but it is important to make the documentation consistent.

2023-03-17 23:32 UTC, sirjoka commented
> Maybe you answered your own question about the code blocks? I tried commenting and then I saw your comment disappear. If you are still thinking about it, I suggest you try consolidating one and inspecting both the PDF and HTML to understand how the code blocks are working.

Yes, I have seen how it works and it answered the questioned. Thank you. 
I have implemented all that was asked I do, and I will now push the update.
Have a lovely weekend. Thank you

2023-03-18 00:18 UTC, sirjoka commented on vignettes/graph.Rmd
> +**complement** to be the graph with the same set of nodes as its input and edges in the complement if there were none in the original graph.
Understood, and implemented as requested.
Thank you

2023-03-20 15:44 UTC, alatiku commented
@Bioconductor/sweave2rmd  
@jwokaty 

On line 269 of first screenshot. Checking the Rnw file (second screenshot), it cites a GrossYellen, which i think is a book 'Graph Theory and Its Applications' (third screenshot), but the name is not right as it only mentions the surname of the authors (Gross & Yellen).   
![image](https://user-images.githubusercontent.com/110193607/226390426-64ef4f4f-d090-4486-bc82-694804c854aa.png)
![image](https://user-images.githubusercontent.com/110193607/226390488-a32e98b5-a13e-46de-9c4e-4c5e917b5506.png)
![image](https://user-images.githubusercontent.com/110193607/226390658-76e3986a-05b3-4829-a3d9-c8949591a306.png)

I am documenting this issue as we await a decision on how to proceed from the Core-Team.

2023-03-20 16:24 UTC, jwokaty commented
> @Bioconductor/sweave2rmd @jwokaty
> 
> On line 269 of first screenshot. Checking the Rnw file (second screenshot), it cites a GrossYellen, which i think is a book 'Graph Theory and Its Applications' (third screenshot), but the name is not right as it only mentions the surname of the authors (Gross & Yellen). ![image](https://user-images.githubusercontent.com/110193607/226390426-64ef4f4f-d090-4486-bc82-694804c854aa.png) ![image](https://user-images.githubusercontent.com/110193607/226390488-a32e98b5-a13e-46de-9c4e-4c5e917b5506.png) ![image](https://user-images.githubusercontent.com/110193607/226390658-76e3986a-05b3-4829-a3d9-c8949591a306.png)
> 
> I am documenting this issue as we await a decision on how to proceed from the Core-Team.

Can you use https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html to create a .bib file with the reference information to the book? It should explain how add pieces to the yaml to use the .bib file. When you knit the file, it should generate the inline reference as well as  reference section at the bottom using the .bib file.

2023-03-20 18:20 UTC, alatiku commented
Ok, I think I have it done.
@jwokaty Please have a look.

2023-03-21 21:48 UTC, jwokaty commented on DESCRIPTION
> +	person("Aliyu Atiku", "Mustapha", role = "ctb",
Line 15 is indented too much. It should be indented the same as line 12.

2023-03-21 21:49 UTC, jwokaty commented on vignettes/graph.Rmd
> +any node in g1 we can find out which nodes are adjacent to it using the adj
Make `g1` bold with `**g1**`

2023-03-21 21:49 UTC, jwokaty commented on vignettes/graph.Rmd
> +function. Both functions are `vectorized`, that is, the user can supply a vector
Since "vectorized" isn't a function, let's just use italics. Use `*vectorized*`.

2023-03-21 21:50 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove extra line.

2023-03-21 21:53 UTC, jwokaty commented on vignettes/graph.Rmd
> +Notice that while the graphs *gR* and *gR2* have different sets of edge weights
Make `*gR*` bold with `**gR**`. Do the same for `*gR2*`.

2023-03-21 23:10 UTC, jwokaty commented on vignettes/graph.Rmd
> +
I think you can remove the extra blank lines in the code blocks since they'll be formatted nicely.

2023-03-21 23:11 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove blank lines 134, 17, 139.

2023-03-21 23:11 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove blank lines 178, 181.

2023-03-21 23:11 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove line 218

2023-03-21 23:12 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove blank lines 261, 264

2023-03-21 23:12 UTC, jwokaty commented on vignettes/graph.Rmd
> +
Remove line 298

2023-03-21 23:15 UTC, jwokaty commented on vignettes/graph.Rmd
> +function. Or we can find out which nodes are accessible from it using the acc
Make `acc` bold

2023-03-21 23:15 UTC, jwokaty commented on vignettes/graph.Rmd
> +correspond to the names of the nodes that were supplied. For acc the elements of
Make `acc` bold

2023-03-21 23:20 UTC, jwokaty commented on vignettes/graph.Rmd
> +subgraph. The boundary returns a named list with one component for each node in
Surround `boundary` with backticks

2023-03-21 23:21 UTC, jwokaty commented on vignettes/graph.Rmd
> +chunk two graphs are created, gR and gR2, the first is undirected while the
Surround `gR` and `gR2` with backticks

2023-03-21 23:23 UTC, jwokaty commented on vignettes/graph.Rmd
> +underlying graph. This is the graph with all edge orientation removed. The
Set `underlying` in italics

2023-03-21 23:26 UTC, jwokaty commented on vignettes/graph.Rmd
> +existing is 0.1. The graph g2 is on the same set of nodes but we specify that it
Surround  `g1` and `g2` with backticks.

2023-03-21 23:29 UTC, jwokaty commented on vignettes/graph.Rmd
> +graph. For a directed graph or digraph the underlying graph is the graph that
Make `directed graph` and `digraph` italics.

2023-03-21 23:32 UTC, jwokaty commented on vignettes/graph.Rmd
> +Biocpkg("RBGL")` package. The returned value is a named vector. The names
The inline R code isn't generating the proper link because it is spread across 2 lines. Move the first part to the second line.

2023-03-21 23:35 UTC, jwokaty commented on vignettes/graph.Rmd
> +between the different representations.
Can lines 320-322 be formatted a little better?

2023-03-21 23:35 UTC, jwokaty commented on vignettes/graph.Rmd
> +Conversion to a `graphNEL` graph can be carried out using the as method for that
Surround `as` with backticks

2023-03-21 23:37 UTC, jwokaty commented on vignettes/graph.Rmd
> +only slot defined in the virtual class is *edgemode* which can be either
Set `edgemode` in backticks rather than making it italics.

2023-03-21 23:38 UTC, jwokaty commented on vignettes/graph.Rmd
> +directed or undirected indicating whether the edges are directed or not.
`directed` and `undirected` should be in italics.

2023-03-21 23:39 UTC, jwokaty commented on vignettes/graph.Rmd
> +  The basic class, `graph`, is a virtual class and all other classes will extend
For lines 349, 355, 359, 362 could you remove the indents?

2023-03-21 23:42 UTC, jwokaty commented on vignettes/graph.Rmd
> +next and will use the *SparseM* package if it is available.
SparseM is a CRAN package. Please use

    `r CRANpkg("SparseM")`

2023-03-21 23:55 UTC, jwokaty commented on vignettes/graph.Rmd
> +no between cluster edges.
After line 364, add a space then add a header for References. The references you made should automatically be applied after that. Check the knitted file to make sure it appears correctly.

Good job on setting the reference up.

2023-03-22 00:00 UTC, jwokaty commented on vignettes/references.bib
> +  year = {2019},
It is 2019 not 2018?

2023-03-22 00:08 UTC, jwokaty requested changes
Good work on the References. The remaining issues are primarily formatting related. Some of them are due to graph being an older package. I ask these changes to make it easier to maintain graph since it will be around for awhile.

After pushing the changes to these request, if everything looks good and no issues remain, your code will be merged into Bioconductor.

2023-03-22 08:57 UTC, sirjoka commented on vignettes/references.bib
> +  year = {2019},
Actually, 2005. And that is the second edition, without "Anderson, M." as an author. 
I have decided to go with back to the 2005 2nd edition version, since graph wasn't written around 2018/2019, and removed "Anderson, M." from the authors.

2023-03-22 18:39 UTC, jwokaty commented on vignettes/graph.Rmd
> +that is a connected component of the *underlying* graph and this is the default
`underlying` should not be italicized in lines 244 and 247.

2023-03-22 18:40 UTC, jwokaty commented on vignettes/graph.Rmd
> +any node in `g1` we can find out which nodes are adjacent to it using the adj
Surround `adj` at the end of the line with backticks since it is a function name.

2023-03-22 19:30 UTC, jwokaty commented on vignettes/graph.Rmd
> +---
Please add `link-citations: yes` to the yaml header so that we get a link to the reference.

2023-03-22 19:31 UTC, jwokaty commented on vignettes/graph.Rmd
> +searching algorithm as described in Algorithm 4.2.1 of [@Algorithm_4_2_1]. More
Remove the brackets. I had to think about it, but the way the sentence is written I think it is better without the brackets.

2023-03-22 19:33 UTC, jwokaty commented
@sirjoka 4 small issues. Please make these and I will merge tomorrow.

2023-03-22 20:09 UTC, sirjoka commented
> @sirjoka 4 small issues. Please make these and I will merge tomorrow.

Yay. All done. Thank you so much for the help and guidance.

2023-03-23 07:51 UTC, devbird007 commented
Hello @sirjoka , you should remove line-7 `package: graph` since you already have the same thing contained within line 13

2023-03-23 09:19 UTC, alatiku commented
> Hello @sirjoka , you should remove line-7 `package: graph` since you already have the same thing contained within line 13

Hi thanks, but line 7 is part of yaml requirement so line 13 is the one that is removable, depending on @jwokaty

2023-03-23 14:12 UTC, devbird007 commented
> > Hello @sirjoka , you should remove line-7 `package: graph` since you already have the same thing contained within line 13
> 
> Hi thanks, but line 7 is part of yaml requirement so line 13 is the one that is removable, depending on @jwokaty

Oh alright, I was just making a suggestion based on what @mcarlsn told me when he was reviewing my work, but yh this should be depending on @jwokaty now.

2023-03-23 14:15 UTC, alatiku commented
> > > Hello @sirjoka , you should remove line-7 `package: graph` since you already have the same thing contained within line 13
> > 
> > Hi thanks, but line 7 is part of yaml requirement so line 13 is the one that is removable, depending on @jwokaty
> 
> Oh alright, I was just making a suggestion based on what @mcarlsn told me when he was reviewing my work, but yh this should be depending on @jwokaty now.

I appreciate that, thank you.

2023-03-23 16:40 UTC, jwokaty commented on vignettes/graph.Rmd
> +that is a connected component of the *underlying* graph and this is the default
I think you missed this: "underlying" should not be italicized. It's line 244 here but in the updated code it is now line 245.

2023-03-23 16:50 UTC, jwokaty commented
@sirjoka It's okay to leave `package` in the yaml.

I don't disagree with the advice @devbird007 received, which was to follow the PDF. Generally, we try to stay very close to the PDF, but I decided to look a little closer at this field. Since we're not altering the original scientific content and it provides version information that might be important for the end user, I think we can keep it going forward but it is not a requirement.

2023-03-23 17:10 UTC, alatiku commented
> @sirjoka It's okay to leave `package` in the yaml.
> 
> I don't disagree with the advice @devbird007 received, which was to follow the PDF. Generally, we try to stay very close to the PDF, but I decided to look a little closer at this field. Since we're not altering the original scientific content and it provides version information that might be important for the end user, I think we can keep it going forward but it is not a requirement.

Yes, keeping the package in the YAML knits the HTML with the package information showing, as per PDF and conversion requirements stated. So I keep it right? Do I remove the "%\VignettePackage{graph}" under the Vignette information then?

2023-03-23 17:23 UTC, jwokaty commented
Leave the yaml header as it is.  Just do https://github.com/Bioconductor/graph/pull/19#pullrequestreview-1353253810.

2023-03-23 19:43 UTC, sirjoka commented
> Leave the yaml header as it is.  Just do https://github.com/Bioconductor/graph/pull/19#pullrequestreview-1353253810.

Will do. Thank you

2023-03-27 14:13 UTC, jwokaty commented
Hi, I am just following up to see if you make the change for https://github.com/Bioconductor/graph/pull/19#pullrequestreview-1353253810.

2023-03-27 16:20 UTC, alatiku commented
Hi, yes, I have made the necessary changes requested. Please review. Thank you

2023-03-27 20:24 UTC, merged

2023-03-27 20:24 UTC, jwokaty commented
I'm merging your code now. Thanks for your contribution!

2023-03-27 20:48 UTC, alatiku commented
Thank you for the opportunity and guidance.