Convert graphAttributes-Rmd
Bioconductor/graph pull request #3
Opened 2022-06-08 17:43 UTC by raoulkam

@jwokaty Kindly review this conversion

2022-06-14 20:37 UTC, jwokaty requested changes
I am repeating a lot of what I stated to Paul since it's the same thing:

- [ ] When we have the `.Rmd` file, we want to remove the corresponding `.Rnw` file. I would do this as a separate commit from your other changes with a precise commit message in case we ever needed to bring it back. To do this in git use `git rm` name_of_file.Rnw.
- [ ] You also need to bump the z number in the version (x.y.z) in the DESCRIPTION file.
- [ ] You probably should also add `BiocStyle` to the `Suggests` list in the DESCRIPTION file since it isn't there now.

Please address these changes, commit, and push your changes. When you `git push origin your-branch-name`, your new commits will be placed after your existing commits on this pull request.

2022-06-14 20:37 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +```{r}
If you compare your html and the original pdf, you'll see that the original is hiding the results, including messages like the other packages it is loading. I think your html should do the same for this code chunk and others where it may be similar on the original pdf.

2022-06-14 20:37 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +g1 <- graphAM(adjMat=mat)
The pdf prints the results of this.

2022-06-14 20:37 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +
I would also suggest removing the extra spaces between sections and keep the width of the text to about 80 characters to make it easier to read.

2022-06-14 20:37 UTC, jwokaty commented on vignettes/graphAttributes.Rmd
> +```{r}
It might be okay to just remove lines 187-194 since they are commented out in the original. If it is something anyone really wants to fix they can refer to the original document.

2022-06-14 22:10 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +title: "Attributes for Graph Objects"
Corrected. Sections now numbered

2022-06-14 22:11 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +*graph-class* would work. See Figure [1](#fig1).
Corrected, link created and work

2022-06-14 22:12 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +Figure 1: The graph `g1`
Image now caption using  fig.cap

2022-06-14 22:12 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +
Corrected

2022-06-14 22:12 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +```{r}
Comments and message hidden

2022-06-14 22:13 UTC, raoulkam commented on vignettes/graphAttributes.Rmd
> +```{r}
Done

2022-07-15 02:11 UTC, jwokaty commented
@raoulkam Do you have additional commits that you haven't pushed yet?

2022-08-04 14:21 UTC, closed without merging