Converting GraphClass.Rnw to GraphClass.Rmd
Bioconductor/graph pull request #9
Opened 2022-10-19 17:07 UTC by Chisomgold

Hi @jwokaty 

I just made the sweave to Rmd conversion for GraphClass.

Attached are the files for comparison: [GraphClass PDF file](https://bioconductor.org/packages/devel/bioc/vignettes/graph/inst/doc/GraphClass.pdf) and [GraphClass HTML file](https://github.com/Bioconductor/graph/files/9822679/GraphClass.zip)

2022-10-24 22:20 UTC, jwokaty requested changes
Great job! I just have a few more items to add for your review. 

- [ ] Can I ask that you also update the `DESCRIPTION` file such that the `Author` section is formatted similar to the [BiocParallel DESCRIPTION file](https://github.com/Bioconductor/BiocParallel/blob/master/DESCRIPTION#L5-L21)? Add yourself as a contributor like the two contributors from line 16.
- [ ] Also, replace the `Maintainer` line with
    ```
    person(
        "Bioconductor Package Maintainer",
        role = "cre",
        email = "maintainer@bioconductor.org"
    )
    ```
- [x] Change the section numbering so that they aren't decimals--e.g., "1" rather than "0.1". I think you can do this by removing an extra `#` for the sections. For example, the first section should be `# Introduction`. Then you should adjust the sections that follow.

2022-10-25 10:40 UTC, Chisomgold commented on vignettes/GraphClass.Rmd
> +`nodes<-(object)` Returns a new graph object with the node labels set as specified by a character vector. This is slightly fragile since the order matters. But the order can only really be determined
Hi @jwokaty 

Thank you for the feedback.

I've made the changes as requested. Here's what the [HTML file looks like now](https://github.com/Bioconductor/graph/files/9859532/GraphClass.zip).

I'll be expecting your remarks

2022-10-26 16:12 UTC, jwokaty requested changes
Hi @Chisomgold,

This looks really good, but I need to ask for one edit because my instructions weren't very good.

Can I ask you in the `DESCRIPTION` file remove the `Maintainer` completely and move the value for it to the `Authors@R` vector. It should look like this:

```
Authors@R: c(
    person("R", "Gentleman", role = "aut"),
    person("Elizabeth", "Whalen", role="aut"),
    person("W", "Huber", role="aut"),
    person("S", "Falcon", role="aut"),
    person("Halimat C.", "Atanda", role = "ctb",
        comment = "Converted 'GraphClass' vignette from Sweave to RMarkdown / HTML."
    ),
    person(
        "Bioconductor Package Maintainer",
        role = "cre",
        email = "maintainer@bioconductor.org"
    ))
```

We're trying to develop this convention to make sure that contributors get credit and also use this new style `Authors@R` to include the maintainer. After this edit, I believe we'll be ready to merge your work into Bioconductor!

2022-10-26 19:45 UTC, Chisomgold commented
All done @jwokaty

2022-10-28 02:41 UTC, jwokaty commented
Great job. Just one comment. Indents in R are typically 4 spaces rather tabs. I went ahead and made the change so we could merge your commit.

2022-10-28 02:43 UTC, merged

2022-10-28 07:44 UTC, Chisomgold commented
Thank you. I'll keep it in mind.